AllCops:
  Exclude: 
    - 'data/**/*'
    - 'vendor/**/*'

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 8


inherit_from: 
  - .rubocop_base.yml
  - .rubocop_todo.yml
