language: ruby
before_install:
  - echo -e "machine github.com\n  login $GITHUB_ACCESS_TOKEN" >> ~/.netrc
script: bundle exec rake close_old_pull_requests pull_request_summary:travis test
cache: bundler
rvm:
  - 2.3.1
env:
  global:
    secure: ZCQVQdKDUyPY/BM1FYriv6h+rNF+PqQETnj5FwU/jQKNz8utvaUVjXD/pIMwEmO5orzng5/MnZvErkr2+JZBs+0JghXWtjDxQHxJzfBTZJnaiAY9hWZBC9Kgbl1/mJvUvK132W5GzQ5xS9lw/pyKFGRba9A7rfoYFfkaJKmgq1U=
deploy:
  provider: script
  # $TRAVIS_RUBY_VERSION will be set to the Ruby version the Travis build uses,
  # which is set in the `rvm` section above.
  # @see https://docs.travis-ci.com/user/deployment/script/#Deployment-is-executed-by-Ruby-1.9.3
  script: rvm $TRAVIS_RUBY_VERSION do scripts/deploy.sh
  on:
    branch: master
